---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mongodb
  namespace: demo
  annotations:
    fluxcd.io/automated: "false"
    fluxcd.io/tag.chart-image: semver:~4.0
    bananas: apples
spec:
  releaseName: mongodb
  interval: 1m
  chart:
    spec:
      chart: mongodb
      version: 7.6.3
      sourceRef:
        kind: HelmRepository
        name: googleapis
        namespace: default
  values:
    image:
      repository: bitnami/mongodb
      tag: 4.0.14
    usePassword: false
    persistence:
      enabled: false
    securityContext:
      enabled: false
      fsGroup: 0
      runAsUser: 0
